# Generated by Django 2.2.4 on 2019-09-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_answer',
            field=models.CharField(max_length=100),
        ),
    ]
